[phases.setup]
nixpkgs = ["python311", "pip", "gcc", "pkg-config", "openssl", "libffi"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python app.py"