[phases.setup]
nixpkgs = ["python311", "gcc", "pkg-config", "openssl", "libffi"]

[phases.install]
cmds = [
    "python3 -m ensurepip --upgrade", 
    "python3 -m pip install --upgrade pip", 
    "pip install -r requirements.txt"
]

[start]
cmd = "python3 app.py"