[phases.setup]
nixpkgs = ["python311", "gcc", "pkg-config", "openssl", "libffi"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",  # Upgrade pip directly
    "pip install -r requirements.txt"       # Install requirements
]

[start]
cmd = "python3 app.py"  # Run your app