"""Initial migration

Revision ID: 1a6a85fc466b
Revises: 
Create Date: 2025-05-26 16:39:33.517831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6a85fc466b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Auth')
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.alter_column('fin_kod',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('collaborators', schema=None) as batch_op:
        batch_op.alter_column('fin_kod',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('fin_kod',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('salary_smeta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('salary_smeta_fin_kod_key'), type_='unique')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('project_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subject_of_purchase', schema=None) as batch_op:
        batch_op.alter_column('project_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_of_purchase', schema=None) as batch_op:
        batch_op.alter_column('project_code',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('project_code',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('salary_smeta', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('salary_smeta_fin_kod_key'), ['fin_kod'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('fin_kod',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('collaborators', schema=None) as batch_op:
        batch_op.alter_column('fin_kod',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('fin_kod',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('Auth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fin_kod', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Auth_pkey')),
    sa.UniqueConstraint('fin_kod', name=op.f('Auth_fin_kod_key'))
    )
    # ### end Alembic commands ###
